### ISSUE TITLE
Add support for .Net Core

### ISSUE THREAD

**Issue by MarcusWichelmann** [fbarresi/Sharp7#1]
Could you please update your NuGet package to support .Net Core? The sharp7 library should work flawlessly on this plattform, but the warning in Visual Studio (because of the wrong target framework) is a little bit annyoing.

**Comment by fbarresi** [comment]
Thank you for your contribution! 
Solved in version 1.0.13

**Comment by MarcusWichelmann** [comment]
Thank you very much! 😄
