### ISSUE TITLE
GetRealAt rounding

### ISSUE THREAD

**Issue by riser1337** [fbarresi/Sharp7#14]
Hi, 
I don't understand why GetRealAt sometimes gives me Numbers like: 182.2499999985 instead of the actual 182.25 inside the PLC.
Anyone also experiences this issue?

**Comment by fbarresi** [comment]
Hi,
That's just normal. A decimal number cannot always be represented as real (float-4bytes) with enough accuracy.
[This article] (http://effbot.org/pyfaq/why-are-floating-point-calculations-so-inaccurate.htm#:~:text=It's%20a%20problem%20caused%20by,resulting%20in%20small%20roundoff%20errors.&text=In%20base%202%2C%201%2F2,8%20%3D%200.001%2C%20etc.%20.) explains the effect.

**Comment by fbarresi** [comment]
If you still have any further questions, please feel free to continue writing into this issue.
Otherwise I will close it.
