### ISSUE TITLE
Suggestion: Keep a change log or make releases + consider using SemVer

### ISSUE THREAD

**Issue by philfontaine** [fbarresi/Sharp7#16]
Please keep a changelog or make releases on github (explaining what's in the release). Otherwise, people have absolutely no idea what they are getting when upgrading the version on Nuget.

Also, you should consider using SemVer https://semver.org/ for your version numbers.

**Comment by fbarresi** [comment]
Hi,
Thank you, you are absolutely right!
I will provide a changelog and reference it in the nuget package as release notes.
