### ISSUE TITLE
Inconveniences in S7.cs

### ISSUE THREAD

**Issue by SGStino** [fbarresi/Sharp7#18]
Instead of using `this`, `SetBitAt` uses `ref`, however `byte[] `is a pointer to the array, so there's no need to ref it.
`        public static void SetBitAt(ref byte[] buffer, int pos, int bit, bool value)`

There also is a cast to `short` in GetIntAt, however the return type is still `int`

And `GetTODAt`/`SetTODAt`/`GetLTODAt`/`SetLTODAt`, work with `DateTime`, while there's no Date part in the data, shouldn't it use `TimeSpan` instead?
(As suggested by the code already present: `TimeSpan Time = value.TimeOfDay;`)

**Comment by fbarresi** [comment]
Hi,
Thank you for your adwices.
I will prepare this enhancements!
Best Regards, 
FB

**Comment by fbarresi** [comment]
fixed in version 1.1.75
