### ISSUE TITLE
support net-5/6?

### ISSUE THREAD

**Issue by tqangxl** [fbarresi/Sharp7#23]
.NET 5.0 is a current release. That means that it will be supported for three months after .NET 6.0 is released. As a result, we expect to support .NET 5.0 through the middle of February 2022. .NET 6.0 will be an LTS release and will be supported for three years, just like .NET Core 3.1.
https://devblogs.microsoft.com/dotnet/announcing-net-5-0/
https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-1/

**Comment by Peter-B-** [comment]
The nuget package of Sharp7 contains a .net standard 2.0 version. This is supported by both .Net 5 and .Net 6.

So you can use sharp7 in a .Net 5 application. I do this and it works just fine.

https://docs.microsoft.com/en-us/dotnet/standard/net-standard
