### ISSUE TITLE
GetIntAt have problem!

### ISSUE THREAD

**Issue by CetinOzdil** [fbarresi/Sharp7#29]
It returns int instead of short and miscalculates value because of that.  
This has been fixed on original sharp7.cs with 1.0.4 update by Jérémy HAURAY at 2018/06/12. 

Problem could be fixed as below;

```c#
  public static short GetIntAt(this byte[] buffer, int pos)
  {
      return (short)((buffer[pos] << 8) | buffer[pos + 1]);
  }
```

**Comment by fbarresi** [comment]
Hi! 
Thank you for reporting it!
I'm fixing it.

Best regards, 
Federico Barresi
