### ISSUE TITLE
Wiki documentation mistake

### ISSUE THREAD

**Issue by somapatrik** [fbarresi/Sharp7#35]
Hello,
I belive that S7300 uses slot 2 not 1.

![obrazek](https://user-images.githubusercontent.com/3592779/226860674-eb3562e2-1cb7-463b-a733-abcc8deb58b5.png)

**Comment by somapatrik** [comment]
Ofcourse it depends on your HW config, however default value is definetly 2.

**Comment by fbarresi** [comment]
Done
