### ISSUE TITLE
Return values in Wiki are wrong

### ISSUE THREAD

**Issue by ganzcooler** [fbarresi/Sharp7#37]
If you go to the [IO functions page](https://github.com/fbarresi/Sharp7/wiki/IO-functions) for example, you will see that the return values are copied from the [Connection page](https://github.com/fbarresi/Sharp7/wiki/Connection).

They are obviously wrong.

**Comment by fbarresi** [comment]
Hi! 

Thank you for rising an issue!
I fixed. 

Best regards, 
FB
