### ISSUE TITLE
S7Client.Connected is always true after connection

### ISSUE THREAD

**Issue by somapatrik** [fbarresi/Sharp7#4]
Tested with S7-300. After successful connection to PLC, if you disconnect it or turn it off the S7Client.Connected property stays always true.

**Comment by fbarresi** [comment]
Hi! 
Thank you for reporting this issue!

This connection property comes directly from System.Net.Sockets.Socket object and it is not notification based.

Look at this [Stackoverflow thread](https://stackoverflow.com/questions/35432912/socket-remains-connected-after-the-remote-computer-closes-it) for an explaination.

For such a case we realized [Sharp7Reactive](https://github.com/evopro-ag/Sharp7Reactive) that also gives you such a notification in form of an IObservable<ConnectionStates> .
